# This example demonstrates two ways to deliver secrets to PODs.

# Notes:
# - Remember secrets are specific to a name spaces.

# Here we setup the secret.
# the secret data is base 64 encoded (yeah, I know... super secure)
# on a *nix systme you can do $ echo -n 'username' | base64
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  labels:
    stackname: fazbear
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi


