apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-3 # xxxx
  namespace: mem-example # xxxx
spec:
  containers:
  - name: memory-demo-3-ctr
    image: busybox
    resources:
      limits:
        memory: "250Mi"
        cpu: "1"
      requests:
        memory: "100Mi"
        cpu: "0.5"