apiVersion: v1
kind: Service
metadata:
  name: example-service-kuard
  labels:
    app: example-service-kuard
spec:
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort
  selector:
    app: example-pod-kuard
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: example-replica-kuard
  labels:
    app: example-replica-kuard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-pod-kuard
    spec:
      containers:
      - name: example-container-kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        ports:
        - containerPort: 8080